<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
<xacro:property name="base_length" value="0.5"/>
<xacro:property name="base_height" value="0.2"/>


    <joint name="camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="${base_length/4} 0 ${base_height/2+0.03/2+0.05}" rpy="0 0 0"/>
    </joint>

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="0.010 0.03 0.03"/>
            </geometry>

        </visual>
        <visual>
            <origin xyz="0 0 ${-0.05/2-0.03/2}"/>
            <geometry>
                <cylinder radius="0.002" length="0.05"/>
            </geometry>

        </visual>
    </link>


    <joint name="camera_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_link"/>        
        <origin xyz="0 0 0" rpy="0 0 0"/>        
    </joint>

    <link name="camera_link"></link>
  <gazebo reference="camera_link">
    <sensor name="camera" type="camera">
      <camera>
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>100</far>
        </clip>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so"/>
    </sensor>
  </gazebo>

</robot>
