/**:
  ros__parameters:
    usingPowerManagementBoard: true
    verbosity: false
    canInterface: eduart-can2
    frequencyScale: 32
    inputWeight: 0.2
    maxPulseWidth: 100
    timeout: 300
    kp: 0.5
    ki: 7.0
    kd: 0.0
    antiWindup: 1
    responseMode: 0
    
    controllers: 2
    
    controller0:
      canID: 0
      drive0: #front right
        channel: 0
        kinematics: [20.0, 20.0, 6.1]
        gearRatio: 89.0
        encoderRatio: 2048.0
        rpmMax: 60.0
        invertEnc: 1
      drive1: #rear right
        channel: 1
        kinematics: [20.0, -20.0, 6.1]
        gearRatio: 89.0
        encoderRatio: 2048.0
        rpmMax: 60.0
        invertEnc: 1

    controller1:
      canID: 1
      drive0: #front left
        channel: 0
        kinematics: [-20.0, 20.0, 6.1]
        gearRatio: 89.0
        encoderRatio: 2048.0
        rpmMax: 60.0
        invertEnc: 1
      drive1: #rear left
        channel: 1
        kinematics: [-20.0, -20.0, 6.1]
        gearRatio: 89.0
        encoderRatio: 2048.0
        rpmMax: 60.0
        invertEnc: 1
